version: "3.8"

services:
  nexus:
    image: 'sonatype/nexus3'
    container_name: ${COMPOSE_PROJECT_NAME}_nexus
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    expose:
      - 8081
      - 8082
      - 8083
    ports:
      - '${DC_NEXUS_HTTP_PORT:-8081}:8081' # http Web-GUI port
      - '${DC_NEXUS_PROXY_PORT:-8082}:8082' # dockerhub proxy
      - '${DC_NEXUS_PRIVATE_PORT:-8083}:8083' # private-docker
    volumes:
      - ./data:/nexus-data
      - ./deploy-plugins:/opt/sonatype/nexus/deploy
